#!/bin/bash
#
# This script will setup the ideal system
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# install software
./install_zsh
./install_homebrew
./install_gems

# install dev
./install_bind
./install_php_stack

# set settings
./set_settings_osx

# done!
cowsay Woohoo! You\'re done.