#!/bin/bash
#
# This script will configure bind to resolve *.dev to 127.0.0.1
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# create a rndc key
sudo rndc-confgen -a -c /etc/rndc.key
sudo chmod 644 /etc/rndc.key

sudo mv /etc/named.conf /etc/named.conf.old
sudo cp ../named/named.conf /etc/named.conf
sudo cp ../named/dev.zone /var/named/dev.zone

# startup on boot
sudo launchctl load -w /System/Library/LaunchDaemons/org.isc.named.plist

# clear DNS
sudo killall -HUP mDNSResponder

echo "Don't forget to add an extra DNS server with ip 127.0.0.1 and reboot your mac"
