#!/bin/bash
#
# This script will install a PHP stack
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# install MySQL
brew install mysql

# Set up databases to run AS YOUR USER ACCOUNT with:
unset TMPDIR
mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp

# To launch on startup:	@todo	werkt niet door de versienummer
mkdir -p ~/Library/LaunchAgents
cp /usr/local/Cellar/mysql/5.5.25a/homebrew.mxcl.mysql.plist ~/Library/LaunchAgents/
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist

# install PHP
brew tap josegonzalez/homebrew-php
brew install php53 --with-mysql --with-intl --with-imap

# fix pear
sudo pear config-set auto_discover 1
sudo pear update-channels
sudo pear upgrade

# install pear packages
sudo pear channel-discover pear.phpunit.de
sudo pear install PHP_Codesniffer

# install
pecl install oauth
pecl install apc

echo "Make MySQL load on startup: "
echo ""
echo "Set MySQL password by using: "
echo "  mysqladmin -u root password 'new-password'"
echo "  mysqladmin -u root -h $(hostname -f) password 'new-password'"
echo "add LoadModule php5_module    /usr/local/Cellar/php53/5.3.14/libexec/apache2/libphp5.so into /etc/apache2/httpd.conf"
