#!/bin/bash
#
# This script will install Homebrew
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>
# install brew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"

# update and upgrade brew
brew doctor
brew update
brew upgrade

# install some packages
brew install cowsay wget git curl mackup ruby
