#!/bin/bash
#
# This script will install some stuff related to our dev
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# MySQL
brew install mysql

# install coffee-script
brew install node
npm install -g coffee-script
