#!/bin/bash
#
# This script will install some stuff related to our dev
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# grab the current dir
CURRENTDIR=$(pwd)

# MySQL
brew install mysql

# install coffee-script
brew install node
npm install -g coffee-script

# install php.ini
sudo ln -s $CURRENTDIR/php/php.ini /etc/php.ini

# install composer
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# install pear and PHPUnit
cd /usr/lib/php &&
sudo php install-pear-nozlib.phar &&
sudo pear channel-update pear.php.net &&
sudo pecl channel-update pecl.php.net &&
sudo pear upgrade-all &&
sudo pear channel-discover pear.phpunit.de  &&
sudo pear channel-discover pear.symfony-project.com &&
sudo pear channel-discover pear.symfony.com &&
sudo pear install --alldeps phpunit/PHPUnit

# install phpcsfixer
curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o /usr/local/bin/phpcsfixer
chmod a+x /usr/local/bin/phpcsfixer

# install phpcodesniffer
sudo pear install PHP_CodeSniffer
