#!/bin/bash
#
# This script will install rvm, http://see rvm.io
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

curl -L https://get.rvm.io | bash -s stable --ruby

source ~/.zshrc

rvm install 1.9.3
rvm use --default 1.9.3