#!/bin/bash
#
# This script will install some gems we like
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

gem install capistrano-ext
gem install forkcms_deploy
gem install sumodev_deploy
gem install compass
gem install css_parser
gem install bundler
gem install librarian-chef
gem install foreman
