#!/bin/bash
#
# This script will install a PHP stack
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# install MySQL
brew install mysql

# Set up databases to run AS YOUR USER ACCOUNT with:
unset TMPDIR
mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp

# To launch on startup:	@todo	werkt niet door de versienummer
mkdir -p ~/Library/LaunchAgents
cp $(brew --prefix mysql)/homebrew.mxcl.mysql.plist ~/Library/LaunchAgents/
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist

# install PHP
brew tap josegonzalez/homebrew-php
brew tap homebrew/dupes
brew install php53 --with-mysql --with-intl --with-imap

# reload the path, so we are using the correct commands
source ~/.zshrc

# symlink the extensions
sudo mv /usr/lib/php/extensions /usr/lib/php/extensions.old
sudo ln -s $(brew --prefix php53)/lib/php/extensions /usr/lib/php/extensions

# fix pear
chmod -R ug+w $(brew --prefix php53)/lib/php
pear config-set php_ini /usr/local/etc/php/5.3/php.ini
pear config-set auto_discover 1
pear update-channels
pear upgrade

# install pear packages
pear channel-discover pear.phpunit.de
pear install PHP_Codesniffer
pear install phpunit/PHPUnit

# install
pecl install oauth
pecl install apc

echo "Set MySQL password by using: "
echo "  mysqladmin -u root password 'new-password'"
echo "  mysqladmin -u root -h $(hostname -f) password 'new-password'"
echo "add LoadModule php5_module    $(brew --prefix php53)/libexec/apache2/libphp5.so into /etc/apache2/httpd.conf"
