#!/bin/bash
#
# This script will install some gems we like
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

sudo gem install capistrano-ext
sudo gem install forkcms_3_deploy
sudo gem install sumodev_deploy
sudo gem install compass
sudo gem install css_parser