#!/bin/bash
#
# This script will create al needed symlinks
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# grab the current dir
CURRENTDIR=$(pwd)
USER=$(whoami)

# check if the file is a symlink, if so it will be removed, if not a backup will be created
function remove_or_backup {
	if [ -h $1 ] 
	then
		rm $1
	else
		if [ -f $1 ]
		then
			mv $1 $1.old
		fi
	fi
}

# install the symlink if the source file exists
function install {
	if [ -f $1 ]
	then
		remove_or_backup $2
		ln -s $CURRENTDIR/$1 $2	
	fi
}

# install the symlink if the source file exists, and replace some vars inside the template
function install_template {
	if [ -f $1 ]
	then
		cp $1 ${1%.template}
		sed -i '' "s/{{USER}}/$USER/" $CURRENTDIR/${1%.template}
		remove_or_backup $2
		ln -s $CURRENTDIR/${1%.template} $2
	fi
}

# git
#install git/.gitignore ~/.gitignore
#install git/.gitconfig ~/.gitconfig

# mysql
#install mysql/.my.cnf ~/.my.cnf

# ssh
#install ssh/config ~/.ssh/config

# zsh
#cp -R $CURRENTDIR/zsh/themes/defv.zsh-theme ~/.oh-my-zsh/themes
#install zsh/.zsh_aliases ~/.zsh_aliases
#install zsh/.zshrc ~/.zshrc

# scripts
#mkdir -p ~/bin
#install bin/new_host ~/bin/new_host
#install bin/dbdump ~/bin/db_dump

# php
install_template php/php.ini.template /usr/local/etc/php/5.3/php.ini

# apache
#sudo mv /etc/apache2/httpd.conf /etc/apache2/httpd.conf.old
#sudo ln -s $CURRENTDIR/apache/httpd.conf /etc/apache2/httpd.conf