#!/bin/bash
#
# This script will create al needed symlinks
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# grab the current dir
CURRENTDIR=$(pwd)

# check if the file is a symlink, if so it will be removed, if not a backup will be created
function remove_or_backup {
	if [ -h $1 ] 
	then
		rm $1
	else
		if [ -f $1 ]
		then
			mv $1 $1.old
		fi
	fi
}

# install the symlink if the source file exists
function install {
	if [ -f $1 ]
	then
		remove_or_backup $2
		ln -s $CURRENTDIR/$1 $2		
	fi
}

# git
install git/.gitignore ~/.gitignore
install git/.gitconfig ~/.gitconfig

# mysql
install mysql/.my.cnf ~/.my.cnf

# ssh
install ssh/config ~/.ssh/config

# zsh
cp -R $CURRENTDIR/zsh/themes/defv.zsh-theme ~/.oh-my-zsh/themes
install zsh/.zsh_aliases ~/.zsh_aliases
install zsh/.zshrc ~/.zshrc

# scripts
mkdir -p ~/bin
install bin/new_host ~/bin/new_host