#!/bin/sh

unset GIT_DIR

OWD=$PWD
PREVIOUS_HEAD=$1
CURRENT_HEAD=$2
BRANCH=$3

if [[ $BRANCH == 0 ]]; then exit; fi

# Go to the current working directory
cd ./$(git rev-parse --show-cdup)

# Let us catch user input
exec < /dev/tty

if [[ -f Procfile ]]; then
  setting=$(git config sumo.compiler.run)

  if [[ "$setting" = "never" ]]; then
    exit 0
  fi

  if [[ "$setting" != "always" ]]; then
    read -p ">> Found Procfile. Run local commands? ([y]es, [n]o, n[e]ver, [a]lways> " choice

    if [[ "$choice" = "n" ]]; then
      exit 0
    elif [[ "$choice" = "e" ]]; then
      $(git config sumo.compiler.run never)
      exit 0
    elif [[ "$choice" = "a" ]]; then
      $(git config sumo.compiler.run always)
    fi
  fi

  cat Procfile | while read line
  do
    name=${line%%: *}
    cmd=${line#*: }

    if [[ "$cmd" =~ "compass watch" ]]; then
      cmd=`echo $cmd | sed 's/ watch/ compile/'`
    elif [[ "$cmd" =~ "coffee" ]]; then
      cmd=`echo $cmd | sed 's/ -w / /'`
    fi

    eval $cmd
  done
else
  # See if we have a compass config
  CONFIGS=$(find . -name config.rb)

  for CONFIG in $CONFIGS; do
    SASS_ROOT_DIR=$(dirname $CONFIG)

    cd $SASS_ROOT_DIR

    HAS_COMPILED_CSS=$(ls css) # Is our CSS already compiled?
    CHANGED_ASSETS=$(git diff --name-only $PREVIOUS_HEAD $CURRENT_HEAD $PWD) # Are assets changed?

    if [ "$CHANGED_ASSETS" ] || ! [ "$HAS_COMPILED_CSS" ]; then
      echo "Compiling SASS"
      compass clean && compass compile -s expanded
    fi
  done

fi

cd $OWD;